name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日実行
  workflow_dispatch:     # 手動実行も可能

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install @octokit/rest fs-extra
        
      - name: Generate stats
        run: node generate-stats.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub stats" && git push)
